/**
 * Formula Parser Utility
 * 
 * Extracts metadata from formula code comments.
 * Formulas generated by the app include metadata comments like:
 * // @provider: groq
 * // @model: qwen/qwen3-32b
 */

export interface FormulaMetadata {
  provider: string;
  model: string;
}

/**
 * Parse metadata from formula string
 * 
 * @param formula - The formula code string
 * @returns Metadata object with provider and model, or null if not found
 * 
 * @example
 * ```typescript
 * const formula = `// @provider: groq\n// @model: qwen/qwen3-32b\nreturn ...`;
 * const metadata = parseFormulaMetadata(formula);
 * // { provider: 'groq', model: 'qwen/qwen3-32b' }
 * ```
 */
export function parseFormulaMetadata(formula: string): FormulaMetadata | null {
  if (!formula || typeof formula !== 'string') {
    return null;
  }

  // Look for metadata comments in the first few lines
  const lines = formula.split('\n').slice(0, 10); // Check first 10 lines only
  
  let provider: string | null = null;
  let model: string | null = null;

  for (const line of lines) {
    const trimmed = line.trim();
    
    // Match: // @provider: groq
    if (trimmed.startsWith('// @provider:')) {
      provider = trimmed.replace('// @provider:', '').trim();
    }
    
    // Match: // @model: qwen/qwen3-32b
    if (trimmed.startsWith('// @model:')) {
      model = trimmed.replace('// @model:', '').trim();
    }
    
    // Stop if we found both
    if (provider && model) {
      break;
    }
  }

  // Return metadata if we found at least the provider
  if (provider) {
    return {
      provider,
      model: model || 'unknown'
    };
  }

  return null;
}

/**
 * Get provider from formula, with fallback to global settings
 * 
 * @param formula - The formula code string
 * @param fallbackProvider - Provider to use if not found in formula (default: 'openai')
 * @returns Provider name
 */
export function getFormulaProvider(formula: string, fallbackProvider: string = 'openai'): string {
  const metadata = parseFormulaMetadata(formula);
  return metadata?.provider || fallbackProvider;
}

/**
 * Get model from formula
 * 
 * @param formula - The formula code string
 * @returns Model name or null if not found
 */
export function getFormulaModel(formula: string): string | null {
  const metadata = parseFormulaMetadata(formula);
  return metadata?.model || null;
}
